name: flutter_fetch_hackernews
description: A new Flutter pet-project - Fetch Hacker News
publish_to: none
version: 1.1.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.6 <2.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/example.db
    - assets/issue_64.db

dependencies:
  path: any
  collection: any
  flutter:
    sdk: flutter
  sqflite:

  cupertino_icons: any
  path_provider: any
  http: any
  rxdart: any

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

